### ISSUE TITLE
PNNL CI Kokkos Cuda arch compatibility

### ISSUE THREAD

**Issue by jaelynlitz** [eagles-project/mam4xx#117]
Currently, our PNNL CI pipelines have 3 gpu partitions available (dl, dlt, dlv) which each have a different cuda arch.  
   - P100 (cuda_arch 60) (dl/dl_shared)
   - V100 (cuda_arch 70) (dlv/dlv_shared)
   - RTX 2080 Ti (cuda_arch 75) (dlt/dlt_shared)

Kokkos errors out if different partitions are selected for building haero vs running mam4xx

Example: haero build on dl (cuda arch 60) then testing on dlt (cuda arch 75) and failing https://code.pnnl.gov/e3sm/eagles/mam4xx/-/jobs/8678 

Suggested fix:
Rebuild haero stage should build for all three partitions, then at the testing stage, the haero path should be selected based on the current partition

Workaround for now:
Hardcode the partition to be dl for tests to run

cc @CameronRutherford @jeff-cohere

**Comment by jeff-cohere** [comment]
Seems like this issue is resolved for the moment. We can revisit CI issues in the RC environment as needed (especially since I'm sure the systems are going to be changing quasi-regularly).
