### ISSUE TITLE
unit_tests (Failed) in Mac

### ISSUE THREAD

**Issue by odiazib** [eagles-project/mam4xx#140]
Hi all, 

All unit tests are failing in my Mac. 
	  1 - utils_unit_tests (Failed)
	  2 - mam4_nucleation_unit_tests (Failed)
	  3 - mam4_gasaerexch_unit_tests (Failed)
	  4 - mam4_coagulation_unit_tests (Failed)
	  5 - mam4_calcsize_unit_tests (Failed)
	  6 - mam4_rename_unit_tests (Failed)
	  7 - mam4_aging_unit_tests (Failed)
	  9 - kohler_unit_tests (Failed)
	 10 - aero_modes_unit_tests (Failed)
	 11 - aero_config_unit_tests (Failed)
	 12 - mode_averages (Failed)
	 13 - conversions_unit_tests (Failed)

With this error:
/bin/sh: build/mam4xx/bin/test-launcher: Permission denied

I am using the main branch. 

My mac:
macOS Monterey version: 12.6.1
compiler: AppleClang 14.0.0.14000029

**Comment by odiazib** [comment]
Hi @mjs271, is this issue that you are having on your Mac?

**Comment by mjs271** [comment]
As it turns out, it wasn't. Just the not-so-helpful error messages coming from compiler 😕
