### ISSUE TITLE
Increasing Code Coverage

### ISSUE THREAD

**Issue by pressel** [eagles-project/mam4xx#186]
This issue is to make note of @overfelt's suggestions for increasing code coverage. In particular, `if` branches in the validation tests that check for the existence of required variables in the validation input files are leading to significant amounts of uncovered code. On one hand , this code is not part of the ported MAM4 code so this lack of coverage does not imply a lack of coverage of the ported code, on the other hand it makes the reported code coverage somewhat less meaningful. 

@overfelt suggests that we can overcome this issue by making use of EKAT, for example:
`EKAT_REQUIRE_MSG(input.has("deltat"), “Required name: detlat");`

could be used to replace 

`
    if (!input.has("deltat")) {
      std::cerr << "Required name: "
                << "detlat" << std::endl;
      exit(1);
    }
`

I would suggest that at some point revisit all existing validation tests and make the above replacement where relevant.

**Comment by jeff-cohere** [comment]
PR #194 removes unit test and validation driver source code from our code coverage reports. I think this is a preferable solution, because we're interested in the actual MAM4xx code that's being tested.
