### ISSUE TITLE
`validate_aer_rad_props_lw_ts_355` test failing on GPU

### ISSUE THREAD

**Issue by jaelynlitz** [eagles-project/mam4xx#287]
We have a failing GPU test `validate_aer_rad_props_lw_ts_355` in main in the aerosol_optics code. It is difficult to see what the problem is in CI since the output gets too long for the log and it cuts off. I ran it on Deception myself to capture the full output and will attach those files (output, mam4xx py file, mam py file)

[aer_rad_props_test_fail_output.txt](https://github.com/eagles-project/mam4xx/files/14089987/aer_rad_props_test_fail_output.txt)
[mam_aer_rad_props_lw_ts_355.txt](https://github.com/eagles-project/mam4xx/files/14089988/mam_aer_rad_props_lw_ts_355.txt)
[mam4xx_aer_rad_props_lw_ts_355.txt](https://github.com/eagles-project/mam4xx/files/14089989/mam4xx_aer_rad_props_lw_ts_355.txt)

cc @jeff-cohere @odiazib

**Comment by jaelynlitz** [comment]
Semi-related question: how would we feel about setting the CI ctest flags to only output on failure to clean up the logs?

**Comment by odiazib** [comment]
I will check these tests.

**Comment by odiazib** [comment]
are these validation tests are failing for PR #273?  Have you rebased youe branch to the main branch? I ran these tests with the main branch in my work station and they are passing.

**Comment by jaelynlitz** [comment]
They are failing in #273 even after rebasing. The logs I posted when opening this issue are from running on main

**Comment by odiazib** [comment]
The failing test should be fixed in the main branch. I just merged PP #285  into the main branch.

**Comment by jaelynlitz** [comment]
Great, thanks @odiazib ! I will close this issue
