### ISSUE TITLE
Should Diagnostics split into interstitial and cloud, to match Prognostics?

### ISSUE THREAD

**Issue by pbosler** [eagles-project/mam4xx#47]
Recent PRs #44 and #36 split `Prognostics` fields for number and mass mixing ratios into distinct cloud (`c`) and interstitial (`i`) categories.   The same likely needs to be done for `Diagnostics` variables such as particle size and hygroscopicity, but it may be trickier than it looks at first.  

1. Wet particle size should likely be separated, as it depends on two different processes: water uptake for interstitial aerosols, droplet activation for clouds.  On the other hand, the water microphysics package might take over all-things "activated," so maybe we don't need to track a separate size for wet cloud particles.

3. Hygroscopicity is an immutable property of the species that make up a mode, so maybe only one value is needed, but the modal mass mixing ratios change the modal average hygroscopicity, so the average hygroscopicity will be different depending on whether the interstitial vs. cloudborne mass mixing ratios are used to compute it, so perhaps two are needed.  If a previously wet cloud particle dries out, its composition will be different than aerosols that had always been interstitial, which is another argument for two hygroscopicity categories.

4. Dry particle size seems likely at first to be an interstitial-only property, but the droplet activation parameterization includes water evaporation from previously-activated aerosols... Since these would be cloudborne before they dry out, their composition will be different than aerosols that were not previously activated, and they would have a different dry size.

The answers likely depend on how such things are used by other processes in MAM4; as we learn/convert more of processes, hopefully the answers will become clear.

**Comment by jeff-cohere** [comment]
Our current approach to "diagnostic quantities" is pretty messy--it's the carpet under which we're sweeping all intermediate variables within aerosol parameterizations. If we get the opportunity to "orthogonalize" all of mam4xx's aerosol processes, we should reexamine the structure of prognostic and diagnostic quantities in terms of interstitial and cloudborne character.
