### ISSUE TITLE
Consolidated set of test utilities

### ISSUE THREAD

**Issue by pbosler** [eagles-project/mam4xx#78]
Now that we're getting more processes converted, we're starting to ask more of our unit tests than just compiling, building, and running without crashing --- we're beginning to want actual results for regression, and if possible, verification.   

PRs #42, #56, #70 and #72 all introduce specified initial states for both aerosols and atmosphere for the purpose of testing nonzero values.  It might be worthwhile to extract these into a single test `AeroConfig`, `Prognostics`, `Diagnostics`, and `Atmosphere` source for all tests to use.

**Comment by jeff-cohere** [comment]
We now have a set of testing utilities in (`testing.hpp`), driven mostly by our unmanaged `ColumnViews` and the need to explicitly allocate storage for them in a testing environment.
