### ISSUE TITLE
Consolidate modal averages

### ISSUE THREAD

**Issue by pbosler** [eagles-project/mam4xx#79]
Computations like modal volume, hygroscopicity, and particle size require averages over modal mass- and/or number-mixing ratios.   These quantities are used in many aerosol processes (they have already shown up in `gasaerxch`, `calcsize`, and water uptake, for example).  Instead of repeating the same computations in several places, we should consolidate such things to a single set of functions.

**Comment by jeff-cohere** [comment]
Our "direct port" strategy unfortunately precludes this. But any future cleanup we do on the code should make a better attempt at reusing implementations and not re-implementing them everywhere.
